# Generated by Django 5.0.9 on 2024-11-02 23:38

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_data_mover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcemodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='datamoverconfig',
            name='fetch_data_definition',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='datamoverconfig',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datamoverconfig',
            name='transformations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DataMoverDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('auth_details', models.JSONField()),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='datamoverconfig',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='netbox_data_mover.datamoverdatasource'),
        ),
        migrations.AlterField(
            model_name='datamoverconfig',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='netbox_data_mover.datamoverdatasource'),
        ),
        migrations.DeleteModel(
            name='DataDestinationModel',
        ),
        migrations.DeleteModel(
            name='DataSourceModel',
        ),
    ]